name: NodeJS with Webpack

on:
  push:
    branches: [ "ww/local-conversion" ]
  pull_request:
    branches: [ "ww/local-conversion" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run build
        sed -e 's#dist/##g' manifest.json > dist/manifest.json
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ico-export-figma-plugin
        path: ${{ github.workspace }}/dist/
